CharRefDict = {
        'oai' : ['xmlns="http://www.openarchives.org/OAI/2.0/"\s*xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\s*xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/\s*http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd"', ''],
        'thesis' : ['xmlns="http://www.ndltd.org/standards/metadata/etdms/1.0/"\s*schemaLocation="http://www.ndltd.org/standards/metadata/etdms/1.0/\s*http://www.ndltd.org/standards/metadata/etdms/1.0/etdms.xsd"', ''],
        'dash' : ['&#8211;', '-'],
        'doubdash' : ['&#8212;', '--'],
        'horizbar' : ['&#8213;', '--'],
        'apos' : ['&#8216;', '&apos;'],
        'apos1' : ['&#8217;', '&apos;'],
        'apos2' : ['&#39;', '&apos;'],
        'slash' : ['&#47;', '/'],
        'fractSlash' : ['&#8260;', '/'],
        'apos3' : ['&#039;', '&apos;'],
        'quo' : ['&#8220;', '&quot;'],
        'quo1' : ['&#8221;', '&quot;'],
        'aster' : ['&#8727;', '*'],
        'doubsp' : ['&#160;', ' '],
        'amp' : ['&#38;', '&amp;'],
        'backsl' : ['&#34;', '&quot;'],
        #Diacritics and spec characters
        'less' : ['&#60;', '&lt;'],
        'greater' : ['&#62;' , '&gt;'],
        'AO' : ['&#160;', '{A0}'],
        'iexcl' : ['&#161;', '{iexcl}'],
        'pound' : ['&#163;', '{pound}'],
        'uml' : ['&#168;', '{uml}'],
        'copy' : ['&#169;', '{copy}'],
        'softhyphen' : ['&#173;', '-'],
        'reg' : ['&#174;', '{reg}'],
        'deg' : ['&#176;', '{deg}'],
        'micro' : ['&#181;', '[micro]'],
        'middot' : ['&#183;', '{middot}'],
        'plusminus' : ['&#177;', '{plusmin}'],
        'graveA' : ['&#192;', '{grave}A'],
        'acuteA' : ['&#193;', '{acute}A'],
        'circA' : ['&#194;', '{circ}A'],
        'tildeA' : ['&#195;', '{tilde}A'],
        'umlA' : ['&#196;', '{uml}A'],
        'ringA' : ['&#197;', '{ring}A'],
        'AElig' : ['&#198;', '{AElig}'],
        'ostroke' : ['&#248;', '{ostrok}'],
        'Ostroke' : ['&#216;', '{Ostrok}'],
        'ZCaron' : ['&#381;', '{caron}Z'],
        'zCaron' : ['&#382;', '{caron}z'],
        'cedilC' : ['&#199;', '{cedil}C'],
        'graveE' : ['&#200;', '{grave}E'],
        'acuteE' : ['&#201;', '{acute}E'],
        'circE' : ['&#202;', '{circ}E'],
        'umlE' : ['&#203;', '{uml}E'],
        'graveO' : ['&#204;', '{grave}I'],
        'acuteI' : ['&#205;', '{acute}I'],
        'circI' : ['&#206;', '{circ}I'],
        'umlI' : ['&#207;', '{uml}I'],
        'tildeN' : ['&#209;', '{tilde}N'],
        'graveO' : ['&#210;', '{grave}O'],
        'acuteO' : ['&#211;', '{acute}O'],
        'circO' : ['&#212;', '{circ}O'],
        'tildeO' : ['&#213;', '{tilde}O'],
        'umlO' : ['&#214;', '{uml}O'],
        'multi' : ['&#215;', 'x'],
        'graveU' : ['&#217;', '{grave}U'],
        'acuteU' : ['&#218;', '{acute}U'],
        'circU' : ['&#219;', '{circ}U'],
        'umlU' : ['&#220;', '{uml}U'],
        'acuteY' : ['&#221;', '{acute}Y'],
        'THORN' : ['&#222;', '{THORN}'],
        'eszett' : ['&#223', 'ss'],
        'gravea' : ['&#224;', '{grave}a'],
        'acutea' : ['&#225;', '{acute}a'],
        'circa' : ['&#226;', '{circ}a'],
        'tildea' : ['&#227;', '{tilde}a'],
        'tilde' : ['&#126;', '{tilde}'],
        'umla' : ['&#228;', '{uml}a'],
        'ringa' : ['&#229;', '{ring}a'],
        'aelig' : ['&#230;', '{aelig}'],
        'cedilc' : ['&#231;', '{cedil}c'],
        'gravee' : ['&#232;', '{grave}e'],
        'acutee' : ['&#233;', '{acute}e'],
        'circe' : ['&#234;', '{circ}e'],
        'umle' : ['&#235;', '{uml}e'],
        'gravei' : ['&#236;', '{grave}i'],
        'acutei' : ['&#237;', '{acute}i'],
        'circi' : ['&#238;', '{circ}i'],
        'umli' : ['&#239;', '{uml}i'],
        'eth' : ['&#240;', '{eth}'],
        'tilden' : ['&#241;', '{tilde}n'],
        'graveo' : ['&#242;', '{grave}o'],
        'acuteo' : ['&#243;', '{acute}o'],
        'circo' : ['&#244;', '{circ}o'],
        'tildeo' : ['&#245;', '{tilde}o'],
        'umlo' : ['&#246;','{uml}o'],
        'graveu' : ['&#249;', '{grave}u'],
        'acuteu' : ['&#250;', '{acute}u'],
        'circu' : ['&#251;', '{circ}u'],
        'umlu' : ['&#252;', '{uml}u'],
        'acutey' : ['&#253;', '{acute}y'],
        'thorn' : ['&#254;', '{thorn}'],
        'umly' : ['&#255;', '{uml}y'],
        'combMacron' : ['&#772;', '{macr}'],
        'Alpha' : ['&#913;', '[Alpha]'],
        'Beta' : ['&#914;', '[Beta]'],
        'Gamma' : ['&#915;', '[Gamma]'],
        'Delta' : ['&#916;', '[Delta]'],
        'Epsilon' : ['&#917;', '[Epsilon]'],
        'Zeta' : ['&#918;', '[Zeta]'],
        'Eta' : ['&#919;', '[Eta]'],
        'Theta' : ['&#920;', '[Theta]'],
        'Iota' : ['&#921;', '[Iota]'],
        'Kappa' : ['&#922;', '[Kappa]'],
        'Lambda' : ['&#923;', '[Lambda]'],
        'Mu' : ['&#924;', '[Mu]'],
        'Nu' : ['&#925;', '[Nu]'],
        'Xi' : ['&#926;', '[Xi]'],
        'Omicron' : ['&#927;', '[Omicron]'],
        'Pi' : ['&#928;', '[Pi]'],
        'Rho' : ['&#929;', '[Rho]'],
        'Sigma' : ['&#931;', '[Sigma]'],
        'Tau' : ['&#932;', '[Tau]'],
        'Upsilon' : ['&#933;', '[Upsilon]'],
        'Phi' : ['&#934;', '[Phi]'],
        'Chi' : ['&#935;', '[Chi]'],
        'Psi' : ['&#936;', '[Psi]'],
        'Omega' : ['&#937;', '[Omega]'],
        'alpha' : ['&#945;', '[alpha]'],
        'beta' : ['&#946;', '[beta]'],
        'gamma' : ['&#947;', '[gamma]'],
        'gamma#' : ['&#947;', '[gamma]'],
        'delta' : ['&#948;', '[delta]'],
        'epsilon' : ['&#949;', '[epsilon]'],
        'zeta' : ['&#950;', '[zeta]'],
        'eta' : ['&#951;', '[eta]'],
        'theta' : ['&#952;', '[theta]'],
        'iota' : ['&#953;', '[iota]'],
        'kappa' : ['&#954;', '[kappa]'],
        'lambda' : ['&#955;', '[lambda]'],
        'mu' : ['&#956;', '[mu]'],
        'nu' : ['&#957;', '[nu]'],
        'xi' : ['&#958;', '[xi]'],
        'omicron' : ['&#959;', '[omicron]'],
        'pi' : ['&#960;', '[pi]'],
        'rho' : ['&#961;', '[rho]'],
        'sigma' : ['&#963;', '[sigma]'],
        'tau' : ['&#964;', '[tau]'],
        'upsilon' : ['&#965;', '[upsilon]'],
        'phi' : ['&#966;', '[phi]'],
        'chi' : ['&#967;', '[chi]'],
        'psi' : ['&#968;', '[psi]'],
        'omega' : ['&#969;', '[omega]'],
        'emspace' : ['&#8195;', '  '],
        'bullet' : ['&#8226;', '{middot}'],
        'elips' : ['&#8230;', ' ... '],
        'tradem' : ['&#8482;', '[TM]'],
        'leftarrow' : ['&#8592;', '<-'],
        'rightarrow' : ['&#8594;', '->'],
        'tilde' : ['&#8764;', '~'],
        'almostEqual' : ['&#8776;', '[almost equal to]'],
        'prime' : ['&#8242;', '{softsign}'],
        'minus' : ['&#8722;', '-'],
        'lesseq' : ['&#8804;', '{under}&lt;'],
        'greateq' : ['&#8805;', '{under}&gt;'],
        'doubgreat' : ['&#8811;', '>>'],
        'dollar' : ['\$', '{dollar}'],
        #numbers
        'sup2' : ['&#178;', '{esc}p2{esc}'],
        'sup3' : ['&#179;', '{esc}p3{esc}'],
        'sub2' : ['&#8322;', '{esc}b2{esc}'],

        #degree punctuation/title fixes
        'MS' : ['<name>MS</name>', '<name>M.S.</name>'],
        'MA' : ['<name>MA</name>', '<name>M.A.</name>'],
        'MCP' : ['<name>MCP</name>', '<name>Master of Community Planning</name>'],
        'PhD' : ['<name>PhD</name>', '<name>Ph.D.</name>'],
        'MARCH' : ['<name>MARCH</name>', '<name>Master of Architecture</name>'],
        'MSARCH' : ['<name>MSARCH</name>', '<name>M.S.</name>'],
        'MDES' : ['<name>MDES</name>', '<name>Master of Design</name>'],
        'MDes' : ['<name>MDes</name>', '<name>Master of Design</name>'],
        'MM' : ['<name>MM</name>', '<name>Master of Music</name>'],
        'EdD' : ['<name>EdD</name>', '<name>Dr. of Education</name>'],
        'DMA' : ['<name>DMA</name>', '<name>Dr. of Musical Arts</name>'],
        'MEd' : ['<name>MEd</name>', '<name>Master of Education</name>'],
        }
